/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-10-28 08:48:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findId_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/login/../common/footer.jsp", Long.valueOf(1603868046000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>아이디 찾기</title>\n");
      out.write("<style>\n");
      out.write("/* 내용부분 */\n");
      out.write("#section-header {\n");
      out.write("\twidth: 70%;\n");
      out.write("\theight: 100%;\n");
      out.write("\tmargin: auto;\n");
      out.write("\tmargin-top: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".find-header {\n");
      out.write("\twidth: 50%;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\theight: 50px;\n");
      out.write("\tbackground: rgb(45, 115, 102);\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#find-pwd {\n");
      out.write("\tfloat: right;\n");
      out.write("\tbackground: rgb(65, 166, 147);\n");
      out.write("\tmargin-left: -10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#find-pwd a {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#find-id h4, #find-pwd h4 {\n");
      out.write("\tmargin-left: 40px;\n");
      out.write("\tmargin-top: 12px;\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\theight: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#find-pwd h4:hover {\n");
      out.write("\tfont-weight: bolder;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#find-pwd:hover {\n");
      out.write("\tbackground: rgb(53, 154, 135);\n");
      out.write("}\n");
      out.write("\n");
      out.write("#content {\n");
      out.write("\tbackground: rgb(242, 242, 242);\n");
      out.write("\twidth: 70%;\n");
      out.write("\tmin-height: 400px;\n");
      out.write("\tmargin: auto;\n");
      out.write("\tclear: both;\n");
      out.write("\tborder: 1px solid rgb(242, 242, 242);\n");
      out.write("}\n");
      out.write("\n");
      out.write("#common {\n");
      out.write("\tmargin-right: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#input-boxes {\n");
      out.write("\tmin-width: 400px;\n");
      out.write("\tmargin: auto;\n");
      out.write("\tpadding-left: 20%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".input-box {\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\twidth: 400px;\n");
      out.write("\theight: 230px;\n");
      out.write("\tbackground: white;\n");
      out.write("\tmargin-top: 50px;\n");
      out.write("\tborder: 2px solid gray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".input-header {\n");
      out.write("\tmargin: 0;\n");
      out.write("\theight: 40px;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tbox-shadow: 0px 5px 5px 0px lightgray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".input-header h4 {\n");
      out.write("\tmargin: auto;\n");
      out.write("\tmargin-left: 10px;\n");
      out.write("\tmargin-top: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 일반회원 */\n");
      out.write("#common-input {\n");
      out.write("\twidth: 300px;\n");
      out.write("\tmargin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("\tfont-size: 12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table tr {\n");
      out.write("\theight: 45px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table td {\n");
      out.write("\tmin-width: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".phone {\n");
      out.write("\twidth: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"number\"]::-webkit-outer-spin-button, input[type=\"number\"]::-webkit-inner-spin-button\n");
      out.write("\t{\n");
      out.write("\t-webkit-appearance: none;\n");
      out.write("\tmargin: 0;\n");
      out.write("}\n");
      out.write("/* 사업자 회원 */\n");
      out.write("#business-input {\n");
      out.write("\twidth: 300px;\n");
      out.write("\tmargin: auto;\n");
      out.write("\tmargin-top: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#div-btn-id {\n");
      out.write("\twidth: 400px;\n");
      out.write("\theight: 40px;\n");
      out.write("\tmargin: auto;\n");
      out.write("\tmargin-top: 30px;\n");
      out.write("\tmargin-bottom: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#IdBtn {\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 100%;\n");
      out.write("\tbackground: rgb(45, 115, 102);\n");
      out.write("\tcolor: white;\n");
      out.write("\tborder: none;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<section>\n");
      out.write("\t\t<div id=\"section-header\">\n");
      out.write("\t\t\t<div class=\"find-header\" id=\"find-id\">\n");
      out.write("\t\t\t\t<h4>아이디 찾기</h4>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"find-header\" id=\"find-pwd\">\n");
      out.write("\t\t\t\t<h4>\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/findPwd.me\">비밀번호 찾기</a>\n");
      out.write("\t\t\t\t</h4>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<article id=\"content\">\n");
      out.write("\t\t\t<form onsubmit=\"return findId();\" method=\"post\"\n");
      out.write("\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/findId\">\n");
      out.write("\t\t\t\t<div id=\"input-boxes\">\n");
      out.write("\t\t\t\t\t<div class=\"input-box\" id=\"common\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-header\" id=\"common-header\">\n");
      out.write("\t\t\t\t\t\t\t<h4>일반회원</h4>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"common-input\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"confirm\"><input type=\"radio\" name=\"confirm\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"emailConfirm();\" id=\"confirm-email\">이메일 인증</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"confirm\"><input type=\"radio\" name=\"confirm\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"phoneConfirm();\" checked=\"checked\" id=\"confirm-phone\">휴대폰\n");
      out.write("\t\t\t\t\t\t\t\t\t\t인증</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>이름</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"userName\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"userName\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"change-name\">휴대폰 번호</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"change-input\" colspan=\"2\"><select\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"phone-first\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option selected value=\"010\">010</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"011\">011</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> - <input type=\"number\" class=\"phone\" name=\"phone-middle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t- <input type=\"number\" class=\"phone\" name=\"phone-last\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<script>\n");
      out.write("\t\t\t\t\t\tfunction emailConfirm() {\n");
      out.write("\t\t\t\t\t\t\t$('#change-name').html(\"이메일 주소\");\n");
      out.write("\t\t\t\t\t\t\t$('#change-input').html(\n");
      out.write("\t\t\t\t\t\t\t\t\t'<input type=\"email\" name=\"email\">');\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\t\t\t\tfunction phoneConfirm() {\n");
      out.write("\t\t\t\t\t\t\t$('#change-name').html(\"휴대폰 번호\");\n");
      out.write("\t\t\t\t\t\t\t$('#change-input')\n");
      out.write("\t\t\t\t\t\t\t\t\t.html(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'<select name=\"phone-first\"><option selected value=\"010\">010</option><option value=\"011\">011</option></select> - <input type=\"number\" class=\"phone\" name=\"phone-middle\"> - <input type=\"number\" class=\"phone\" name=\"phone-last\">');\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t<div class=\"input-box\" id=\"business\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-header\" id=\"business-header\">\n");
      out.write("\t\t\t\t\t\t\t<h4>사업자 회원</h4>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"business-input\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>사업주</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"ownName\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"ownName\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>사업자 등록번호</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"number\" name=\"ownNumber\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"div-btn-id\">\n");
      out.write("\t\t\t\t\t<input type=\"submit\" id=\"IdBtn\" value=\"아이디 찾기\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<script>\n");
      out.write("\t\t\t\tfunction findId() {\n");
      out.write("\t\t\t\t\tvar name = $('#userName');\n");
      out.write("\t\t\t\t\tvar own = $('#ownName');\n");
      out.write("\t\t\t\t\tvar phone = $('.phone');\n");
      out.write("\n");
      out.write("\t\t\t\t\tconsole.log(name);\n");
      out.write("\t\t\t\t\tconsole.log(phone);\n");
      out.write("\n");
      out.write("\t\t\t\t\tconsole.log(\"name.val : \" + name.val);\n");
      out.write("\t\t\t\t\tconsole.log(\"name.focus : \" + name.focus());\n");
      out.write("\n");
      out.write("\t\t\t\t\tif (name.val == \"\" || name.length == 0) {\n");
      out.write("\t\t\t\t\t\talert('이름을 입력해주세요');\n");
      out.write("\t\t\t\t\t\tname.focus();\n");
      out.write("\t\t\t\t\t\t$('#userName').focus();\n");
      out.write("\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t} else if (own.val == 0 || own.length == 0) {\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\treturn true;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t</article>\n");
      out.write("\t</section>\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("\tfooter{\n");
      out.write("\t\tmargin-top: 50px;\n");
      out.write("\t\tbottom: 0;\n");
      out.write("\t\tpadding-top: 16px;\n");
      out.write("\t\twidth: 100%;\n");
      out.write("\t\theight: 100px;\n");
      out.write("\t\tbackground: #41A693;\n");
      out.write("\t\tmin-width: 500px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.f_div1 {\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.f_div1 span{\n");
      out.write("\t\tfont-size: 16px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tcolor : white;\n");
      out.write("\t\tpadding: 2px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.f_div1 p{\n");
      out.write("\t\tfont-size: 12px;\n");
      out.write("\t\tmargin: auto;\n");
      out.write("\t\tcolor: white;\n");
      out.write("\t}\n");
      out.write("\t.f_div1 a{\n");
      out.write("\t\ttext-decoration: none;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<footer>\n");
      out.write("\t\t<div class=\"f_div1\">\n");
      out.write("\t\t\t<a href=\"#\"><span>About</span></a>\n");
      out.write("\t\t\t<span> | </span>\n");
      out.write("\t\t\t<span>Privacy</span>\n");
      out.write("\t\t\t<span> | </span>\n");
      out.write("\t\t\t<span>Feedback</span>\n");
      out.write("\t\t\t<span> | </span>\n");
      out.write("\t\t\t<a href=\"#\"><span>Top</span></a>\n");
      out.write("\t\t\t<p><a href=\"https://github.com/vegiter/vegiter_web\">채채식 팀 GitHub</a></p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
