/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-11-07 12:05:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.about;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import login.model.vo.Member;

public final class aboutPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/about/../common/footer.jsp", Long.valueOf(1604461117772L));
    _jspx_dependants.put("/WEB-INF/views/about/../common/gnb.jsp", Long.valueOf(1604460327201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("login.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<!-- 폰트   -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@900&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("#zeroArea {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("\tfont-family: 'Noto Sans JP', sans-serif;\r\n");
      out.write("\tfont-size: 34px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main_div1 {\r\n");
      out.write("\t/*  \t\tborder: 1px solid lightgray;  */\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\tmargin: 50px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sub_title {\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".about {\r\n");
      out.write("\tborder: 1px solid lightgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3, h2 {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#about_arti_1 {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#about_arti_2 {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#about_arti_3 {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("\tmargin-top: -10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser  = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>GNB</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body, div, span, img, header, nav, ul, li{margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline; text-decoration: none; border-style: none; color: #000000; list-style: none;}\r\n");
      out.write("\tbody{line-height: 1;}\r\n");
      out.write("\t.gnb{width: 100%; height:62px; border-bottom: 1px solid lightgray; min-width: 800px; position: fixed; top: 0; background-color: #fff; text-align: center;}\r\n");
      out.write("\t.gnb-nav ul{width: 80%; max-width: 1000px;  min-width: 800px; margin: auto; display: flex; flex-direction : row; text-align: center;}\r\n");
      out.write("\t#logo {width: 130px;}\r\n");
      out.write("\t.gnb-nav-list{left: 0; width: 90px; cursor: pointer; margin: auto; text-align: center; line-height: 50px;}\r\n");
      out.write("\t.gnb-nav-list:nth-child(1){margin-right: 200px;}\r\n");
      out.write("\t.gnb-nav-list:nth-child(1):hover{border: none; margin-right: 200px;}\r\n");
      out.write("\t.gnb-nav-list:hover {font-weight: bold; border-bottom: 3px solid #41A693;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"gnb\">\r\n");
      out.write("\t\t<nav class=\"gnb-nav\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\"><img id=\"logo\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\" src=\"");
      out.print( request.getContextPath() );
      out.write("/images/common/logo.png\" style=\"cursor: pointer;\"></li>\r\n");
      out.write("\t\t\t\t<li  class=\"gnb-nav-list\" onclick=\"location.href = '");
      out.print( request.getContextPath() );
      out.write("/aboutPage.me'\">About</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\">식당검색</li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/recipe'\">레시피</li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/vegiTalk'\">VegiTalk</li>\r\n");
      out.write("\t\t\t\t");
if(loginUser == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/login.me'\">Login</li>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/myPage'\">My Info</li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"zeroArea\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<article>\r\n");
      out.write("\t\t\t<div id=\"main_div1\">\r\n");
      out.write("\t\t\t\t<div id=\"title_div\">\r\n");
      out.write("\t\t\t\t\t<h3 id=\"title\">Vegiter</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"about_div1\" class=\"about\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"sub_title\">소개</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<article class=\"arti\" id=\"arti_1\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print( request.getContextPath() );
      out.write("/images/about/about_arti1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"about_arti_1\">\r\n");
      out.write("\t\t\t\t\t</article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"sub_div1\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-justify\">Vegiter는 건강한 채식에 관한 홍보 및 정보제공을 위해 만들어\r\n");
      out.write("\t\t\t\t\t\t\t졌습니다. 1970년대 이래로 세계적으로 영양과잉과 이로인하여 심혈관질환, 당뇨, 암, 비만 등 다양한 만성질환의\r\n");
      out.write("\t\t\t\t\t\t\t수가 증가하고 있습니다. 뿐만 아니라 세계적인 노령화는 건강한 노후에 대한 화두를 던지고 있습니다. 영양과잉으로 인한\r\n");
      out.write("\t\t\t\t\t\t\t만성질환의 증가와 노령화라는 두가지 주제는 의료비의 상승과 국가재정에 대한 위협의 결과를 낳고, 이것은 다시\r\n");
      out.write("\t\t\t\t\t\t\t국민복지에 대한 부담으로 작용하게 되었습니다. 보다 생산적이고 미래지향적이며 공동체의 행복을 위해 구성된 국가기반의\r\n");
      out.write("\t\t\t\t\t\t\t복지정책들이 의료비로 인하여 소모적으로 변질되고 있는것입니다. 이러한 시점에서 근본원인인 건강한 먹거리에 대한\r\n");
      out.write("\t\t\t\t\t\t\t과학적인 연구가 세계적으로 진행되고 있습니다. 본 Vegiter는 건강한 채식중심의 식생활에 대한 과학적인 정보를\r\n");
      out.write("\t\t\t\t\t\t\t일반시민들에게 제공함으로써 보다 건강하고 미래지향적이며 행복한 미래건설에 일익을 담당하고자 하는 목적을 가지고\r\n");
      out.write("\t\t\t\t\t\t\t있습니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"about_div2\" class=\"about\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"sub_title\">비건이란?</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"sub_div1\">\r\n");
      out.write("\t\t\t\t\t\t<p>채식 혹은 채식주의 하면 무엇이 생각나나요? 고기를 먹지 않고 채소나 과일 같은 식물성 음식만 먹는\r\n");
      out.write("\t\t\t\t\t\t\t것이라고 생각하고 있나요? 사실 채식에는 여러 종류가 있답니다. 채소만 먹는 채식부터 달걀이나 우유는 먹거나,\r\n");
      out.write("\t\t\t\t\t\t\t생선이나 닭고기까지는 먹는 채식도 있지요. 고기는 NO! 채식주의 그렇다면 채식을 하는 사람들은 맛있는 고기를 도대체\r\n");
      out.write("\t\t\t\t\t\t\t왜 안 먹는 걸까요? 이유는 사람마다 다르지만 건강을 위해서인 경우도 있고, 동물과 환경을 보호하기 위해서인 경우도\r\n");
      out.write("\t\t\t\t\t\t\t있어요. 스님처럼 종교적인 이유로 채식을 하는 경우도 있지요. 제레미 리프킨의 《육식의 종말》이라는 책을 보면,\r\n");
      out.write("\t\t\t\t\t\t\t인간의 육식을 위해 키워지는 전세계 12억 8000마리의 소들이 전세계 토지의 24퍼센트를 차지하고 있으며, 미국의\r\n");
      out.write("\t\t\t\t\t\t\t경우 곡물의 70퍼센트를 가축이 먹어치운다고 해요. 반대로 리어 키스의 책 《채식의 배신》을 보면, 채식의 의도는\r\n");
      out.write("\t\t\t\t\t\t\t좋지만 건강을 위해 혹은 환경 오염의 해결책으로 채식을 하는 것은 잘못된 것이라며 채식보다 더 나은 대안을 찾을 수\r\n");
      out.write("\t\t\t\t\t\t\t있다고 하지요. 육식이냐 채식이냐 잡식이냐는 누구도 강요할 수 없는 것이며 무엇을 먹을지는 자신이 결정하는 거예요.\r\n");
      out.write("\t\t\t\t\t\t\t하지만 무엇을 먹을 것인가 생각하며, 건강과 환경을 한 번 더 생각해 보는 것은 의미 있는 일이겠지요?</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h4 class=\"sub_title\">비건의 시대, 마이너에서 메이저로 ! 비거니즘</h4>\r\n");
      out.write("\t\t\t\t\t<article class=\"arti\" id=\"arti_1\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print( request.getContextPath() );
      out.write("/images/about/about_arti2.png\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"about_arti_2\">\r\n");
      out.write("\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div id=\"sub_div1\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t인간과 지구가 생존하기 위한 필수불가결한 선택인지도 모른다. 식품을 넘어 패션, 화장품 등으로 빠르게 번져나가는\r\n");
      out.write("\t\t\t\t\t\t\t비건('Vegan')의 바람은 올해 소비 트랜드를 뒤흔드는 강력한 키워드로 떠올랐다. 육식을 거부하고 동물의 가죽으로\r\n");
      out.write("\t\t\t\t\t\t\t만든 옷을 입지 않으며, 안정성을 빌미로 동물 실험을 자행한 화장품에 대해 불매에 나선 비건! 그들의 목소리는 더\r\n");
      out.write("\t\t\t\t\t\t\t이상 외곽에서 울리던 아싸(아웃사이더)가 아니다. <br> <br> '채밍아웃'이란 단어를\r\n");
      out.write("\t\t\t\t\t\t\t들어봤는가? 채식을 지향하는 것을 커밍아웃 했다 라는 뜻에서 비롯한 신조어이다. 대중적이지 못한 소수의 고백이란\r\n");
      out.write("\t\t\t\t\t\t\t의미가 담겨있다<br> 하지만 '채식주의가 유별나다'라고 생각했던 시정도 사라지고 있다 <br>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"about_div3\" class=\"about\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"sub_title\">채식의 단계</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<article class=\"arti\" id=\"arti_1\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print( request.getContextPath() );
      out.write("/images/about/about_arti3.png\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"about_arti_3\">\r\n");
      out.write("\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\tfooter{\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\tbottom: 0;\r\n");
      out.write("\t\tpadding-top: 16px;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tbackground: #41A693;\r\n");
      out.write("\t\tmin-width: 500px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 span{\r\n");
      out.write("\t\tfont-size: 16px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tcolor : white;\r\n");
      out.write("\t\tpadding: 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 p{\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t.f_div1 a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"f_div1\">\r\n");
      out.write("\t\t\t<a href=\"#\"><span>About</span></a>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Privacy</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Feedback</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<a href=\"#\"><span>Top</span></a>\r\n");
      out.write("\t\t\t<p><a href=\"https://github.com/vegiter/vegiter_web\">채채식 팀 GitHub</a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
