/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-11-09 17:36:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.recipe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.*;
import java.util.ArrayList;
import login.model.vo.Member;

public final class recipeView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/recipe/../common/footer.jsp", Long.valueOf(1604461117772L));
    _jspx_dependants.put("/WEB-INF/views/recipe/../common/gnb.jsp", Long.valueOf(1604460327201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("login.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
 
		Board board=(Board)request.getAttribute("board");
		
    	ArrayList<Attachment> atList=(ArrayList<Attachment>)request.getAttribute("fileList");
    	
		Attachment titleImg=atList.get(0);
    	
    	ArrayList<Content> conList=(ArrayList<Content>)request.getAttribute("conList");
    	
    	Content titleCon=conList.get(0);
    	
    	ArrayList<Comments> list = (ArrayList<Comments>)request.getAttribute("list");
    	
    	BookMark bookList=(BookMark)request.getAttribute("bookList");
    	

    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t#post-img{width: 100%; height: auto;}\r\n");
      out.write("\tbutton{outline: none; background-color: white;border-style: none;}\r\n");
      out.write("\t.title{text-align: center; margin-bottom:20px;}\r\n");
      out.write("\tol, ul{list-style: none;}\r\n");
      out.write("\t .comment{\r\n");
      out.write("\t\twidth: 800px;\r\n");
      out.write("\t\theight:auto;\r\n");
      out.write("\t\tbackground-color: #F3F3F3;  \r\n");
      out.write("\t\tpadding: 18px;\r\n");
      out.write("\t\tmargin-left:350px;\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t\t} \r\n");
      out.write("\r\n");
      out.write("\t.write-img{margin-left:450px; width: 600px; height:330px; overflow: hidden; background-color: #F0F3F5; text-align: center; line-height: 550px;}\r\n");
      out.write("\t#post-img{width: 100%; height: auto;border-radius: 5px; }\r\n");
      out.write("\t.wrapper{margin-top:100px;}\r\n");
      out.write("\t.card-img{border-radius: 5px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t.comment-list{width: 100%;padding: 0;display: inline-block;}\r\n");
      out.write("\t.comment-input{display: flex;justify-content: space-between;margin-top: 20px;vertical-align: middle;}\r\n");
      out.write("\t#comUserId{width: 20%;font-weight: bold;overflow: hidden;}\r\n");
      out.write("\t#comContent{width: 65%;}\r\n");
      out.write("\t#comDate{width: 15%;text-align: right;}\r\n");
      out.write("\t.comment-input-field{width: 85%;border-style: none;padding: 8px; outline:none;}\r\n");
      out.write("\t.comment-input-submit{width: 60px;}\r\n");
      out.write("\t.comment-input-submit:hover{background-color: #41A693;color: #fff;} \r\n");
      out.write("\t.commentRow{padding-top: 12px;}\r\n");
      out.write("\r\n");
      out.write("\t/*-------------------------*/\r\n");
      out.write("\t/* .comment{box-sizing:border-box;width: 500px;background-color: #F0F3F5; height: auto;padding: 14px; margin-top: 8px;}\r\n");
      out.write("\t.comment-list{width: 100%; padding: 0; display: inline-block; margin-top: 8px;}\r\n");
      out.write("\t.comment-input{display: flex; justify-content: space-between; margin-top: 20px; vertical-align: middle;}\r\n");
      out.write("\t#comUserId{display: inline-block; width: 15%; bold; overflow: hidden; font-size: 14px; font-weight: bold !important; height: 20px !important;}\r\n");
      out.write("\t#comContent{display: inline-block; width: 60%; font-size: 14px; height: 20px !important;}\r\n");
      out.write("\t#comDate{display: inline-block; width: 20%; text-align: right; font-size: 14px;\r\n");
      out.write("\t\t\t height: 20px !important;}\r\n");
      out.write("\t.commentRow{padding-top: 12px;}\r\n");
      out.write("\t.comment-input-field{width: 85%;border-style: none; padding: 8px; outline:none;}\r\n");
      out.write("\t.comment-input-submit{width: 50px;}\r\n");
      out.write("\t.comment-input-submit:hover{background-color: #41A693;color: #fff;} */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/*------------------------*/\r\n");
      out.write("\t\r\n");
      out.write("\t#title{font-size: 30px;}\r\n");
      out.write("\t#top{margin-left:300px;}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t.content {width: 600px; min-height: 80px; height: auto; padding: 15px; line-height: 1.5; resize:none;\r\n");
      out.write("\tmargin-left:450px;margin-top:10px; outline: none; border-style: none; color:#6B6B6B; font-weight:bold}\r\n");
      out.write("\t.form-control{width: 800px; min-height: 80px; height: auto; padding: 15px; line-height: 1.5;\r\n");
      out.write("\t resize:none;margin-top:10px; outline: none; border-style: none; background-color:white; }\r\n");
      out.write("\t.part{margin-left:100px;}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t#update{margin-left:1100px;}\r\n");
      out.write("\t#update button{ background-color:#E2F3E6; border-radius: 5px; outline: none;}\r\n");
      out.write("\t#update>button:hover{background-color:#41A693}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfa-bookmark{font-size: 15px;cursor: pointer;}\r\n");
      out.write("\t.fa-bookmark:hover{cursor: pointer;\tcolor: #41A693;}\r\n");
      out.write("\t\r\n");
      out.write("\t#bookMark{color:gray;}\r\n");
      out.write("\t#bookMarkchecked{color:green;}\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.social{width: 1000px;display: flex;justify-content: flex-end;margin: 10px 0; margin-left:150px;}\r\n");
      out.write("\tspan>i {font-size: 18px;vertical-align: middle;}\r\n");
      out.write("\t.social>span{padding: 3px;padding-left: 8px;padding-right: 8px; }\r\n");
      out.write("\t.social>span:nth-child(1):hover{cursor: default;}\r\n");
      out.write("\t.social>span:nth-child(2):hover{cursor: pointer;color:#00FC8F;border-radius: 15px;}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style> \r\n");
      out.write("<script src=\"https://kit.fontawesome.com/34238d14b4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath());
      out.write("/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser  = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>GNB</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body, div, span, img, header, nav, ul, li{margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline; text-decoration: none; border-style: none; color: #000000; list-style: none;}\r\n");
      out.write("\tbody{line-height: 1;}\r\n");
      out.write("\t.gnb{width: 100%; height:62px; border-bottom: 1px solid lightgray; min-width: 800px; position: fixed; top: 0; background-color: #fff; text-align: center;}\r\n");
      out.write("\t.gnb-nav ul{width: 80%; max-width: 1000px;  min-width: 800px; margin: auto; display: flex; flex-direction : row; text-align: center;}\r\n");
      out.write("\t#logo {width: 130px;}\r\n");
      out.write("\t.gnb-nav-list{left: 0; width: 90px; cursor: pointer; margin: auto; text-align: center; line-height: 50px;}\r\n");
      out.write("\t.gnb-nav-list:nth-child(1){margin-right: 200px;}\r\n");
      out.write("\t.gnb-nav-list:nth-child(1):hover{border: none; margin-right: 200px;}\r\n");
      out.write("\t.gnb-nav-list:hover {font-weight: bold; border-bottom: 3px solid #41A693;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"gnb\">\r\n");
      out.write("\t\t<nav class=\"gnb-nav\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\"><img id=\"logo\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\" src=\"");
      out.print( request.getContextPath() );
      out.write("/images/common/logo.png\" style=\"cursor: pointer;\"></li>\r\n");
      out.write("\t\t\t\t<li  class=\"gnb-nav-list\" onclick=\"location.href = '");
      out.print( request.getContextPath() );
      out.write("/aboutPage.me'\">About</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\">식당검색</li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/recipe'\">레시피</li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/vegiTalk'\">VegiTalk</li>\r\n");
      out.write("\t\t\t\t");
if(loginUser == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/login.me'\">Login</li>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/myPage'\">My Info</li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"title\">\t\t\t\r\n");
      out.write("\t\t\t<span id=\"title\"><b>");
      out.print(board.getBoard_title() );
      out.write("</b></span>\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t\t\t<span id=\"userId\">");
      out.print(board.getMem_id());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"date\"><b><br>");
      out.print(board.getBoard_date() );
      out.write("</b></span>\t\r\n");
      out.write("\t\t\t\t\t ");
if(bookList ==null){ 
      out.write("\t\t \t\r\n");
      out.write("\t\t\t\t\t<i class=\"far fa-bookmark\" id=\"bookMark\"></i>\r\n");
      out.write("\t\t\t\t\t ");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<i class=\"far fa-bookmark\" id=\"bookMarkchecked\"></i>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write(" \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t <script>\r\n");
      out.write("\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginUser != null) { 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\tvar num=0;\r\n");
      out.write("\t\t\t\t\t\t\tvar bId=");
      out.print(board.getBoard_no());
      out.write(";\r\n");
      out.write("\t\t\t\t\t\t\tvar user=\"");
      out.print(loginUser.getMemId());
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t$('#bookMark').click(function(){\t\t/*선택*/\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl:'Check_bookmark.recipe',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata:{bId:bId,user:user},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t\t\t\t\tlocation.reload();\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("/*-----------------------------------------------------------------------------------------------------------------*/\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$('#bookMarkchecked').click(function(){\t\t/*선택해제*/\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl:'Uncheck_bookmark.recipe',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata:{bId:bId,user:user},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t\t\t\t\tlocation.reload();\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t");
 } else{
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$('#bookMark').click(function(){\t\t/*선택*/\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.alert('로그인후 가능합니다.');\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t});\t\r\n");
      out.write("\t\t\t\t\t</script> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<span id=\"update\">\r\n");
      out.write("\t\t\t\t<button id=\"delete\" onclick=\"deleteRecipe()\"><b>삭제</b></button>\r\n");
      out.write("\t\t\t\t<button id=\"modify\" onclick=\"updateRecipe()\"><b>수정</b></button>\r\n");
      out.write("\t\t\t\t</span>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tfunction deleteRecipe(){\r\n");
      out.write("\t\t\t\t\tvar bool=confirm(\"정말로 삭제하시겠습니까?\");\r\n");
      out.write("\t\t\t\t\tvar bcate=");
      out.print(board.getBoard_cate());
      out.write(";\r\n");
      out.write("\t\t\t\t\tvar bId=");
      out.print(board.getBoard_no());
      out.write(";\r\n");
      out.write("\t\t\t\t\tif(bool){\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/delete.recipe?bId=\" + bId + \"&bcate=\" +bcate; \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfunction updateRecipe(){\r\n");
      out.write("\t\t\t\t\tvar bool=confirm(\"정말로 수정하시겠습니까?\");\r\n");
      out.write("\t\t\t\t\tvar bcate=");
      out.print(board.getBoard_cate());
      out.write(";\r\n");
      out.write("\t\t\t\t\tvar bId=");
      out.print(board.getBoard_no());
      out.write(";\r\n");
      out.write("\t\t\t\t\tif(bool){\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/update.recipe?bId=\" + bId + \"&bcate=\" +bcate;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t<div id=\"thumbnail\">\r\n");
      out.write("\t\t<div class=\"write-img\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/thumnail_uploadFiles/");
      out.print(titleImg.getAtcName());
      out.write("\" id=\"post-img\" alt=\"비어있습니다.\">\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<textarea class=\"content\" readonly>");
      out.print(titleCon.getContent() );
      out.write("</textarea>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
for(int i=1; i<atList.size(); i++){ 
      out.write("\r\n");
      out.write("  \t\t<div class=\"part\">\r\n");
      out.write(" \t\t\t\t<br><br><br>\r\n");
      out.write(" \t\t\t<div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea1\">\r\n");
      out.write("   \t\t\t \t\t<img id=\"contentImg");
      out.print(i );
      out.write("\" class=\"card-img\" width=\"300\" height=\"300\"\r\n");
      out.write("   \t\t\t \t\t src=\"");
      out.print(request.getContextPath() );
      out.write("/thumnail_uploadFiles/");
      out.print(atList.get(i).getAtcName());
      out.write("\">\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t<textarea class=\"form-control\" name=\"content\" id=\"content1\" aria-label=\"With textarea\"\r\n");
      out.write("    \t\t  \t\t\t\t cols=\"500\" rows=\"9\" disabled  style=\"background-color:transparent\">\r\n");
      out.write("    \t\t  \t\t\t\t ");
if(conList.get(i).getContent()==null){
    		  					 
    		  				 }else{ 
      out.write("\r\n");
      out.write("    \t\t  \t\t\t\t \r\n");
      out.write("    \t\t  \t\t\t\t ");
      out.print(conList.get(i).getContent() );
      out.write("\r\n");
      out.write("    \t\t  \t\t\t\t ");
} 
      out.write("</textarea>\r\n");
      out.write("      \t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write(" \t\t</div>\r\n");
      out.write(" \t");
} 
      out.write("\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write("\t\r\n");
      out.write("\t\t\t");
for(int i=0; i<conList.size(); i++){
					System.out.println(i+":"+conList.get(i).getContent());
					
			}
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"social\">\r\n");
      out.write("\t\t\t<span><i class=\"far fa-comment-dots\" id=\"commentImg\"></i>\r\n");
      out.write("\t\t\t\t");
      out.print(board.getBoard_com());
      out.write("+</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<span class=\"social-item checked\" id=\"likeButton\">\r\n");
      out.write("\t\t\t<i class=\"far fa-heart\" >\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"veguntype\" value=0>\r\n");
      out.write("\t\t\t</i>\r\n");
      out.write("\t\t\t\t<b id=\"likescale\">");
      out.print(board.getBoard_like() );
      out.write("+</b></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tvar num=0;\r\n");
      out.write("\t\t\tvar like=");
      out.print(board.getBoard_like() );
      out.write(";\r\n");
      out.write("\t\t\tvar bId=");
      out.print(board.getBoard_no());
      out.write(";\r\n");
      out.write("\t\t\t$('#likeButton').click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write(" \t\t\t\tnum++;\r\n");
      out.write(" \t\t\t\tconsole.log(num);\r\n");
      out.write(" \t\t\t\tif(num % 2 !=0){\r\n");
      out.write(" \t\t\t\t\t$(this).css({'background':'#41A693','border-radius':'15px','color':'#FF3F3F'});\r\n");
      out.write(" \t\t\t\t\t$(this).children().eq(1).text(++like +\"+\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(this).css({'background':'white','color':'black'});\r\n");
      out.write("\t\t\t\t\t$(this).children().eq(1).text(--like +\"+\");\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write(" \t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl:'updateLike.recipe',\r\n");
      out.write("\t\t\t\t\t\tdata:{num:num,bId:bId},\r\n");
      out.write("\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write(" \t<div class=\"comment\">\t\t\r\n");
      out.write("\t\t\t<ul class=\"comment-list\" id=\"commentSelect\">\r\n");
      out.write("\t\t\t");
 if(list.isEmpty()) {
      out.write("\r\n");
      out.write("\t\t\t\t<span style=\"color: gray; font-size: 14px;\">");
      out.print( board.getMem_id() );
      out.write("님과 가장 먼저 댓글로 이야기해보세요!</span>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t");
 		for(int i = 0; i < list.size(); i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row commentRow\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-2 commentCol\" id='comUserId'>");
      out.print( list.get(i).getMemId() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-7 commentCol\" id='comContent'>");
      out.print( list.get(i).getComContent() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-3 commentCol\" id='comDate'>");
      out.print(  list.get(i).getComDate()  );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t  ");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
 if(loginUser != null) { 
      out.write("\r\n");
      out.write("\t\t<div class=\"comment-input\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"user\" value=\"");
      out.print(loginUser.getMemId() );
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"comment-input-field\" placeholder=\"댓글을 입력하세요.\"  id=\"commentContent\">\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"comment-input-submit\" id=\"addComment\">등록</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<div class=\"comment-input\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"comment-input-field\" placeholder=\"댓글을 입력하세요.\"  id=\"commentContentNot\">\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"comment-input-submit\" id=\"addCommentNot\">등록</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\t$('#commentContentNot').click(function(){\r\n");
      out.write("\t\t\t\t\twindow.alert('로그인 후 가능합니다.');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#addCommentNot').click(function(){\r\n");
      out.write("\t\t\t\t\twindow.alert('로그인 후 가능합니다.');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t $('#addComment').click(function(){\r\n");
      out.write("\t\t \tvar loginUserId=$('.comment-input').children().eq(0).val();\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\tif(loginUserId != null) {\r\n");
      out.write("\t\t\t\tvar writer = loginUserId;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar bId =  '");
      out.print( board.getBoard_no() );
      out.write("';\r\n");
      out.write("\t\t\tvar content = $('#commentContent').val();\t//댓글입력한 곳\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 수 추가\r\n");
      out.write("\t\t\tif(content == null || content == '') {\r\n");
      out.write("\t\t\t\talert(\"댓글을 입력해주세요\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: 'countComment.recipe',\r\n");
      out.write("\t\t\t\t\tdata: {bId:bId},\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: 'insertComment.recipe',\r\n");
      out.write("\t\t\t\t\tdata: {writer:writer, bId:bId, content:content},\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#commentSelect').html('');\r\n");
      out.write("\t\t\t\t\t$('#commentContent').val('');\t// 댓글 입력 후 기존 내용 삭제\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar commentResult = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i=0 in data){\r\n");
      out.write("\t\t\t\t\t\tcommentResult += \"<br><div class='col-2 commentCol' id='comUserId'>\" + data[i].memId + \"</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ \"<div class='col-7 commentCol' id='comContent'>\" + data[i].comContent + \"</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ \"<div class='col-3 commentCol' id='comDate'>\" + data[i].comDate + \"</div> <br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$('#commentSelect').html('<div class=\"row commentRow\">' + commentResult + '</div>');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\tfooter{\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\tbottom: 0;\r\n");
      out.write("\t\tpadding-top: 16px;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tbackground: #41A693;\r\n");
      out.write("\t\tmin-width: 500px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 span{\r\n");
      out.write("\t\tfont-size: 16px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tcolor : white;\r\n");
      out.write("\t\tpadding: 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 p{\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t.f_div1 a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"f_div1\">\r\n");
      out.write("\t\t\t<a href=\"#\"><span>About</span></a>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Privacy</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Feedback</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<a href=\"#\"><span>Top</span></a>\r\n");
      out.write("\t\t\t<p><a href=\"https://github.com/vegiter/vegiter_web\">채채식 팀 GitHub</a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
