/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-11-07 12:56:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.recipe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import login.model.vo.Member;

public final class recipeWriteForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/recipe/../common/footer.jsp", Long.valueOf(1604461117772L));
    _jspx_dependants.put("/WEB-INF/views/recipe/../common/gnb.jsp", Long.valueOf(1604460327201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("login.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("\tfooter,section,.inputtext{display:block;}\t\r\n");
      out.write("\tarticle{margin-top:30px;}\r\n");
      out.write("\t.cardwrap{display:inline-block;}\t\r\n");
      out.write("\tform{padding: 50px;margin-left: 100px;margin-right: 100px;}\r\n");
      out.write("\t\r\n");
      out.write("\t.form-control{display:inline-block;resize: none; }\r\n");
      out.write("\t\r\n");
      out.write("\t#titleImgArea{\r\n");
      out.write("\t\tmargin-left:400px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#content1{\r\n");
      out.write("\t\tmargin-left:380px;\r\n");
      out.write("\t\twidth:500px; height:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#tileImgtitle,#contentname{\r\n");
      out.write("\t\tmargin-left:200px;\r\n");
      out.write("\t\tcolor:gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.card-img,.card{\r\n");
      out.write("\t\tborder:2px dashed darkgray;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.row no-gutters,card-img{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(".select-script{position:relative; width:200px; height:32px; line-height:30px; border:1px solid #606976; border-radius:4px; text-transform:uppercase; background:#fffff; }\r\n");
      out.write(".select-script label{position:absolute; width:90%; font-size:.70em; color:#606976; top:0; left:0; padding:0 5%;}\r\n");
      out.write(".select-script label:after{content:'▼'; width:40px; height:30px; position:absolute; top:0; right:0; font-size:.70em; color:#fff; text-align:center; background:#606976;}\r\n");
      out.write(".select-script select{width:100%; height:40px; opacity:0; filter:alpha(opacity=0); -ms-filter:alpha(opacity=0);}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<title>Vegiter</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <section>\r\n");
      out.write(" \t\r\n");
      out.write("  \t\t\t\r\n");
      out.write("\t  \t\r\n");
      out.write("  <article class=\"writeform\">\t\r\n");
      out.write("  \r\n");
      out.write("  <form action=\"");
      out.print(request.getContextPath());
      out.write("/insert.recipe\" onsubmit=\"return writeBoard();\" method=\"post\"  encType=\"multipart/form-data\">\t\t\r\n");
      out.write("  \t\t<div class=\"insertArea\">\r\n");
      out.write(" \t\t\t <div class=\"input-group input-group-sm mb-3\">\r\n");
      out.write(" \t\t <div class=\"input-group-prepend\">\r\n");
      out.write(" \t\t\t   <span class=\"input-group-text\" id=\"inputGroup-sizing-sm\">title</span>\r\n");
      out.write(" \t\t </div>\r\n");
      out.write(" \t\t\t <input type=\"text\" class=\"form-control\" aria-label=\"Sizing example input\" aria-describedby=\"inputGroup-sizing-sm\" name=\"title\">\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("  \t\t\t\r\n");
      out.write(" \r\n");
      out.write("<div class=\"select-box select-script\">\r\n");
      out.write("    <label for=\"selectbox\">선택해 주세요</label>\r\n");
      out.write("    <select id=\"selectbox\" title=\"선택 구분\" name=\"cate\">\r\n");
      out.write("        <option selected=\"selected\" value=\"0\">선택해 주세요</option>\r\n");
      out.write("        <option value=\"1\">비건</option>\r\n");
      out.write("        <option value=\"2\">락토</option>\r\n");
      out.write("        <option value=\"3\">오보</option>\r\n");
      out.write("        <option value=\"4\">락토오보</option>\r\n");
      out.write("        <option value=\"5\">페스코</option>\r\n");
      out.write("        <option value=\"6\">폴로</option>\r\n");
      out.write("        <option value=\"7\">플렉</option>\r\n");
      out.write("    </select>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t $(document).ready(function(){\t\t \r\n");
      out.write("\t    var select = $('.select-script select');\r\n");
      out.write("\t    select.change(function(){\r\n");
      out.write("\t        var select_name = $(this).children('option:selected').text();\r\n");
      out.write("\t        $(this).siblings(\"label\").text(select_name);\r\n");
      out.write("\t    });\r\n");
      out.write("\t \r\n");
      out.write("\t}); \r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t<table id=\"insertThumbTable\">\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"titleImgArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"tileImgtitle\"><b>THUMBNAIL</b></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"titleImg\" class=\"card\" width=\"500\" height=\"300\">\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\" id=\"content1\" aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\t\t\t<div>\r\n");
      out.write(" \t\t\t\t\t\t\t<br><br><br><div id=\"contentname\"><b>content</b></div><br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea0\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg1\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea1\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg2\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea2\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg3\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\" aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea3\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg4\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\" aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea4\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg5\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea5\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg6\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea6\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg7\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea7\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg8\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\" aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea8\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg9\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea9\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg10\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t  <div>\r\n");
      out.write(" \t\t\t\t\t\t\t \t<br><br><br>\r\n");
      out.write(" \t\t\t\t\t\t\t \t <div class=\"row no-gutters\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t<div class=\"col-md-4\" id=\"titleImgArea10\">\r\n");
      out.write("   \t\t\t \t\t\t\t\t\t\t<img id=\"contentImg11\" class=\"card-img\" width=\"300\" height=\"300\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t     <div class=\"col-md-8\">\r\n");
      out.write("    \t\t\t\t\t\t \t\t\t <div class=\"card-body\">\r\n");
      out.write("    \t\t  \t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\"></textarea>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("     \t\t\t\t   \t \t\t  </div>\r\n");
      out.write("  \t\t\t\t\t\t\t   </div>\r\n");
      out.write(" \t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"fileArea\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg0\" multiple=\"multiple\" name=\"thumbnailImg0\" onchange=\"LoadImg(this,0)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg1\" multiple=\"multiple\" name=\"thumbnailImg1\" onchange=\"LoadImg(this,1)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg2\" multiple=\"multiple\" name=\"thumbnailImg2\" onchange=\"LoadImg(this,2)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg3\" multiple=\"multiple\" name=\"thumbnailImg3\" onchange=\"LoadImg(this,3)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg4\" multiple=\"multiple\" name=\"thumbnailImg4\" onchange=\"LoadImg(this,4)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg5\" multiple=\"multiple\" name=\"thumbnailImg5\" onchange=\"LoadImg(this,5)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg6\" multiple=\"multiple\" name=\"thumbnailImg6\" onchange=\"LoadImg(this,6)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg7\" multiple=\"multiple\" name=\"thumbnailImg7\" onchange=\"LoadImg(this,7)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg8\" multiple=\"multiple\" name=\"thumbnailImg8\" onchange=\"LoadImg(this,8)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg9\" multiple=\"multiple\" name=\"thumbnailImg9\" onchange=\"LoadImg(this,9)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg10\" multiple=\"multiple\" name=\"thumbnailImg10\" onchange=\"LoadImg(this,10)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"thumbnailImg11\" multiple=\"multiple\" name=\"thumbnailImg11\" onchange=\"LoadImg(this,11)\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#fileArea\").hide();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg0\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea0\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg1\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea1\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg2\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea2\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg3\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea3\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg4\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea4\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg5\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea5\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg6\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea6\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg7\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea7\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg8\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea8\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg9\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea9\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg10\").click();\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t$(\"#titleImgArea10\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#thumbnailImg11\").click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction LoadImg(value,num){\r\n");
      out.write("\t\t\t\t\t\tif(value.files && value.files[0]){\r\n");
      out.write("\t\t\t\t\t\t\tvar reader =new FileReader();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\treader.onload=function(e){\r\n");
      out.write("\t\t\t\t\t\t\t\tswitch(num){\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 0: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#titleImg\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 1:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg1\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 2: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg2\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 3:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg3\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 4:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg4\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 5:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg5\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 6:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg6\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 7:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg7\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 8:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg8\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 9:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg9\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 10:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg10\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\tcase 11:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#contentImg11\").attr(\"src\", e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\treader.readAsDataURL(value.files[0]);\r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"btnArea\">\t\r\n");
      out.write("  \t\t\t<input class=\"btn btn-success\" type=\"submit\" value=\"Submit\" >\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t</form>\r\n");
      out.write("  \t\t<script>\r\n");
      out.write("  \t\t\tfunction writeBoard(){\r\n");
      out.write("  \t\t\t\tvar a=$(\"#selectbox\").val();\r\n");
      out.write("  \t\t\t\tif(a==0){\r\n");
      out.write("  \t\t\t\t\talert(\"카테고리를 선택해주세요\");\r\n");
      out.write("  \t\t\t\t\treturn false;\r\n");
      out.write("  \t\t\t\t}else{\r\n");
      out.write("  \t\t\t\t\treturn true;\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t</script>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t</article>\t\t\r\n");
      out.write("\r\n");
      out.write(" </section>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser  = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>GNB</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body, div, span, img, header, nav, ul, li{margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline; text-decoration: none; border-style: none; color: #000000; list-style: none;}\r\n");
      out.write("\tbody{line-height: 1;}\r\n");
      out.write("\t.gnb{width: 100%; height:62px; border-bottom: 1px solid lightgray; min-width: 800px; position: fixed; top: 0; background-color: #fff; text-align: center;}\r\n");
      out.write("\t.gnb-nav ul{width: 80%; max-width: 1000px;  min-width: 800px; margin: auto; display: flex; flex-direction : row; text-align: center;}\r\n");
      out.write("\t#logo {width: 130px;}\r\n");
      out.write("\t.gnb-nav-list{left: 0; width: 90px; cursor: pointer; margin: auto; text-align: center; line-height: 50px;}\r\n");
      out.write("\t.gnb-nav-list:nth-child(1){margin-right: 200px;}\r\n");
      out.write("\t.gnb-nav-list:nth-child(1):hover{border: none; margin-right: 200px;}\r\n");
      out.write("\t.gnb-nav-list:hover {font-weight: bold; border-bottom: 3px solid #41A693;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"gnb\">\r\n");
      out.write("\t\t<nav class=\"gnb-nav\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\"><img id=\"logo\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\" src=\"");
      out.print( request.getContextPath() );
      out.write("/images/common/logo.png\" style=\"cursor: pointer;\"></li>\r\n");
      out.write("\t\t\t\t<li  class=\"gnb-nav-list\" onclick=\"location.href = '");
      out.print( request.getContextPath() );
      out.write("/aboutPage.me'\">About</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\">식당검색</li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/recipe'\">레시피</li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/vegiTalk'\">VegiTalk</li>\r\n");
      out.write("\t\t\t\t");
if(loginUser == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/login.me'\">Login</li>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/myPage'\">My Info</li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\tfooter{\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\tbottom: 0;\r\n");
      out.write("\t\tpadding-top: 16px;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tbackground: #41A693;\r\n");
      out.write("\t\tmin-width: 500px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 span{\r\n");
      out.write("\t\tfont-size: 16px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tcolor : white;\r\n");
      out.write("\t\tpadding: 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 p{\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t.f_div1 a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"f_div1\">\r\n");
      out.write("\t\t\t<a href=\"#\"><span>About</span></a>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Privacy</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Feedback</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<a href=\"#\"><span>Top</span></a>\r\n");
      out.write("\t\t\t<p><a href=\"https://github.com/vegiter/vegiter_web\">채채식 팀 GitHub</a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
