/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-11-09 12:36:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.recipe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.*;
import java.util.ArrayList;

public final class recipeEditForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/recipe/../common/footer.jsp", Long.valueOf(1604461117772L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");

   Board board=(Board)request.getAttribute("board");
   ArrayList<Attachment> atList=(ArrayList<Attachment>)request.getAttribute("fileList");
   Attachment titleImg=atList.get(0);
   ArrayList<Content> conList=(ArrayList<Content>)request.getAttribute("conList");
   Content titleCon=conList.get(0);
   int cate = board.getBoard_cate();
   String[] checkCate = new String[8];
   switch(cate){
   case 1 : checkCate[0] = "selected"; break;
   case 2 : checkCate[1] = "selected"; break;
   case 3 : checkCate[2] = "selected"; break;
   case 4 : checkCate[3] = "selected"; break;
   case 5 : checkCate[4] = "selected"; break;
   case 6 : checkCate[5] = "selected"; break;
   case 7 : checkCate[6] = "selected"; break;
   default : checkCate[7] = "selected"; break;
   }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\r\n");
      out.write("<style>\r\n");
      out.write("   \r\n");
      out.write("   footer,section,.inputtext{display:block;}   \r\n");
      out.write("   article{margin-top:30px;}\r\n");
      out.write("   .cardwrap{display:inline-block;}   \r\n");
      out.write("   form{padding: 50px;margin-left: 100px;margin-right: 100px;}\r\n");
      out.write("   \r\n");
      out.write("   .form-control{display:inline-block;resize: none; }\r\n");
      out.write("   \r\n");
      out.write("   #titleImgArea{\r\n");
      out.write("      margin-left:400px;\r\n");
      out.write("   }\r\n");
      out.write("   #content1{\r\n");
      out.write("      margin-left:380px;\r\n");
      out.write("      width:500px; height:auto;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   #tileImgtitle,#contentname{\r\n");
      out.write("      margin-left:200px;\r\n");
      out.write("      color:gray;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .card-img,.card{\r\n");
      out.write("      border:2px dashed darkgray;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .row no-gutters,card-img{\r\n");
      out.write("      position:absolute;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write(".select-script{position:relative; width:200px; height:32px; line-height:30px; border:1px solid #606976; border-radius:4px; text-transform:uppercase; background:#fffff; }\r\n");
      out.write(".select-script label{position:absolute; width:90%; font-size:.70em; color:#606976; top:0; left:0; padding:0 5%;}\r\n");
      out.write(".select-script label:after{content:'▼'; width:40px; height:30px; position:absolute; top:0; right:0; font-size:.70em; color:#fff; text-align:center; background:#606976;}\r\n");
      out.write(".select-script select{width:100%; height:40px; opacity:0; filter:alpha(opacity=0); -ms-filter:alpha(opacity=0);}\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("<title>Vegiter</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <section>\r\n");
      out.write("    \r\n");
      out.write("  <article class=\"writeform\">   \r\n");
      out.write("  \r\n");
      out.write("  <form action=\"");
      out.print(request.getContextPath());
      out.write("/insert.recipe\" onsubmit=\"return writeBoard();\" method=\"post\"  encType=\"multipart/form-data\">      \r\n");
      out.write("        <div class=\"insertArea\">\r\n");
      out.write("           <div class=\"input-group input-group-sm mb-3\">\r\n");
      out.write("        <div class=\"input-group-prepend\">\r\n");
      out.write("             <span class=\"input-group-text\" id=\"inputGroup-sizing-sm\">title</span>\r\n");
      out.write("        </div>\r\n");
      out.write("           <input type=\"text\" class=\"form-control\" aria-label=\"Sizing example input\" aria-describedby=\"inputGroup-sizing-sm\" name=\"title\" value=\"");
      out.print(board.getBoard_title());
      out.write("\">\r\n");
      out.write("      </div>         \r\n");
      out.write("           \r\n");
      out.write(" \r\n");
      out.write("\t<div class=\"select-box select-script\">\r\n");
      out.write("    \t<label for=\"selectbox\">선택해 주세요</label>\r\n");
      out.write("    \t<select id=\"selectbox\" title=\"선택 구분\" name=\"cate\">\r\n");
      out.write("        \t<option value=\"0\" ");
      out.print( checkCate[7]);
      out.write(">선택해 주세요</option>\r\n");
      out.write("        \t<option value=\"1\" ");
      out.print( checkCate[0]);
      out.write(">비건</option>\r\n");
      out.write("        \t<option value=\"2\" ");
      out.print( checkCate[1]);
      out.write(">락토</option>\r\n");
      out.write("        \t<option value=\"3\" ");
      out.print( checkCate[2]);
      out.write(">오보</option>\r\n");
      out.write("        \t<option value=\"4\" ");
      out.print( checkCate[3]);
      out.write(">락토오보</option>\r\n");
      out.write("        \t<option value=\"5\" ");
      out.print( checkCate[4]);
      out.write(">페스코</option>\r\n");
      out.write("        \t<option value=\"6\" ");
      out.print( checkCate[5]);
      out.write(">폴로</option>\r\n");
      out.write("        \t<option value=\"7\" ");
      out.print( checkCate[6]);
      out.write(">플렉</option>\r\n");
      out.write("    \t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("   <script>\r\n");
      out.write("    $(document).ready(function(){       \r\n");
      out.write("       var select = $('.select-script select');\r\n");
      out.write("       select.change(function(){\r\n");
      out.write("           var select_name = $(this).children('option:selected').text();\r\n");
      out.write("           $(this).siblings(\"label\").text(select_name);\r\n");
      out.write("       });\r\n");
      out.write("    \r\n");
      out.write("   }); \r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   <br>\r\n");
      out.write("      <table id=\"insertThumbTable\">         \r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <div id=\"titleImgArea\">\r\n");
      out.write("                           <div id=\"tileImgtitle\"><b>THUMBNAIL</b></div>\r\n");
      out.write("                        ");
if(titleImg != null){
      out.write("\r\n");
      out.write("                        <img id=\"titleImg\" class=\"card\" width=\"500\" height=\"300\" src=\"");
      out.print( request.getContextPath());
      out.write("/thumnail_uploadFiles/");
      out.print(titleImg.getAtcName());
      out.write("\">   \r\n");
      out.write("                        \r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"card-body\">\r\n");
      out.write("                              <textarea class=\"form-control\" name=\"content\" id=\"content1\" aria-label=\"With textarea\" cols=\"500\" rows=\"9\">");
      out.print(conList.get(0).getContent());
      out.write("</textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>                                       \r\n");
      out.write("      </table>\r\n");
      out.write("      ");
for(int i = 0; i < 11; i++){
      out.write("\r\n");
      out.write("                  <div>\r\n");
      out.write("                      <br><br><br><div id=\"contentname\"><b>content</b></div><br><br><br>\r\n");
      out.write("                           <div class=\"row no-gutters\">\r\n");
      out.write("                               <div class=\"col-md-4\" id=\"titleImgArea");
      out.print(i-1);
      out.write("\">\r\n");
      out.write("             ");
if(i <= atList.size()){ 
      out.write("\r\n");
      out.write("            ");
if(atList.get(i) != null){ 
      out.write("\r\n");
      out.write("                                  <img id=\"contentImg");
      out.print(i);
      out.write("\" class=\"card-img\" width=\"300\" height=\"300\" src=\"");
      out.print( request.getContextPath());
      out.write("/thumnail_uploadFiles/");
      out.print(atList.get(i).getAtcName());
      out.write("\">\r\n");
      out.write("                            \r\n");
      out.write("             ");
}
      out.write("\r\n");
      out.write("          ");
}else{
      out.write("\r\n");
      out.write("                               <img id=\"contentImg");
      out.print(i);
      out.write("\" class=\"card-img\" width=\"300\" height=\"300\" >\r\n");
      out.write("          ");
} 
      out.write("   \r\n");
      out.write("                            </div>\r\n");
      out.write("                              <div class=\"col-md-8\">\r\n");
      out.write("                                 <div class=\"card-body\">\r\n");
      out.write("                                    <textarea class=\"form-control\" name=\"content\"  aria-label=\"With textarea\" cols=\"500\" rows=\"9\">");
      out.print(conList.get(i).getContent());
      out.write("</textarea>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                 \r\n");
      out.write("     \t  ");
 } 
      out.write("    \r\n");
      out.write(" \t");
} 
      out.write(" \r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("            <div id=\"fileArea\">\r\n");
      out.write("               \r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg0\" multiple=\"multiple\" name=\"thumbnailImg0\" onchange=\"LoadImg(this,0)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg1\" multiple=\"multiple\" name=\"thumbnailImg1\" onchange=\"LoadImg(this,1)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg2\" multiple=\"multiple\" name=\"thumbnailImg2\" onchange=\"LoadImg(this,2)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg3\" multiple=\"multiple\" name=\"thumbnailImg3\" onchange=\"LoadImg(this,3)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg4\" multiple=\"multiple\" name=\"thumbnailImg4\" onchange=\"LoadImg(this,4)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg5\" multiple=\"multiple\" name=\"thumbnailImg5\" onchange=\"LoadImg(this,5)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg6\" multiple=\"multiple\" name=\"thumbnailImg6\" onchange=\"LoadImg(this,6)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg7\" multiple=\"multiple\" name=\"thumbnailImg7\" onchange=\"LoadImg(this,7)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg8\" multiple=\"multiple\" name=\"thumbnailImg8\" onchange=\"LoadImg(this,8)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg9\" multiple=\"multiple\" name=\"thumbnailImg9\" onchange=\"LoadImg(this,9)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg10\" multiple=\"multiple\" name=\"thumbnailImg10\" onchange=\"LoadImg(this,10)\">\r\n");
      out.write("               <input type=\"file\" id=\"thumbnailImg11\" multiple=\"multiple\" name=\"thumbnailImg11\" onchange=\"LoadImg(this,11)\">               \r\n");
      out.write("            </div>\r\n");
      out.write("                  \r\n");
      out.write("            <script>\r\n");
      out.write("               $(function(){\r\n");
      out.write("                  $(\"#fileArea\").hide();\r\n");
      out.write("                  \r\n");
      out.write("                  $(\"#titleImgArea\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg0\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  \r\n");
      out.write("                  $(\"#titleImgArea0\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg1\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea1\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg2\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea2\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg3\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea3\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg4\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea4\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg5\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea5\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg6\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea6\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg7\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea7\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg8\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea8\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg9\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  $(\"#titleImgArea9\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg10\").click();\r\n");
      out.write("                  })\r\n");
      out.write("                  $(\"#titleImgArea10\").click(function(){\r\n");
      out.write("                     $(\"#thumbnailImg11\").click();\r\n");
      out.write("                  });\r\n");
      out.write("                  \r\n");
      out.write("               });\r\n");
      out.write("            \r\n");
      out.write("               function LoadImg(value,num){\r\n");
      out.write("                  if(value.files && value.files[0]){\r\n");
      out.write("                     var reader =new FileReader();\r\n");
      out.write("                     \r\n");
      out.write("                     reader.onload=function(e){\r\n");
      out.write("                        switch(num){\r\n");
      out.write("                        case 0: \r\n");
      out.write("                           $(\"#titleImg\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 1:\r\n");
      out.write("                           $(\"#contentImg1\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 2: \r\n");
      out.write("                           $(\"#contentImg2\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 3:\r\n");
      out.write("                           $(\"#contentImg3\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 4:\r\n");
      out.write("                           $(\"#contentImg4\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 5:\r\n");
      out.write("                           $(\"#contentImg5\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 6:\r\n");
      out.write("                           $(\"#contentImg6\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 7:\r\n");
      out.write("                           $(\"#contentImg7\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 8:\r\n");
      out.write("                           $(\"#contentImg8\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 9:\r\n");
      out.write("                           $(\"#contentImg9\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 10:\r\n");
      out.write("                           $(\"#contentImg10\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                        case 11:\r\n");
      out.write("                           $(\"#contentImg11\").attr(\"src\", e.target.result);\r\n");
      out.write("                           break;\r\n");
      out.write("                           \r\n");
      out.write("                        }\r\n");
      out.write("                     }\r\n");
      out.write("                     reader.readAsDataURL(value.files[0]);\r\n");
      out.write("                  }                  \r\n");
      out.write("               }\r\n");
      out.write("            </script>                                    \r\n");
      out.write("         </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"btnArea\">   \r\n");
      out.write("           <input class=\"btn btn-success\" type=\"submit\" value=\"Submit\" >\r\n");
      out.write("        </div>\r\n");
      out.write("     \r\n");
      out.write("     </form>\r\n");
      out.write("        <script>\r\n");
      out.write("           function writeBoard(){\r\n");
      out.write("              var a=$(\"#selectbox\").val();\r\n");
      out.write("              if(a==0){\r\n");
      out.write("                 alert(\"카테고리를 선택해주세요\");\r\n");
      out.write("                 return false;\r\n");
      out.write("              }else{\r\n");
      out.write("                 return true;\r\n");
      out.write("              }\r\n");
      out.write("           }\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("     </article>      \r\n");
      out.write("\r\n");
      out.write(" </section>\r\n");
      out.write("      \r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\tfooter{\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\tbottom: 0;\r\n");
      out.write("\t\tpadding-top: 16px;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tbackground: #41A693;\r\n");
      out.write("\t\tmin-width: 500px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 span{\r\n");
      out.write("\t\tfont-size: 16px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tcolor : white;\r\n");
      out.write("\t\tpadding: 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 p{\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t.f_div1 a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"f_div1\">\r\n");
      out.write("\t\t\t<a href=\"#\"><span>About</span></a>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Privacy</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Feedback</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<a href=\"#\"><span>Top</span></a>\r\n");
      out.write("\t\t\t<p><a href=\"https://github.com/vegiter/vegiter_web\">채채식 팀 GitHub</a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
