/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-11-08 06:22:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.recipe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import board.model.vo.*;
import login.model.vo.Member;

public final class recipelist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/recipe/../common/footer.jsp", Long.valueOf(1604461117772L));
    _jspx_dependants.put("/WEB-INF/views/recipe/../common/gnb.jsp", Long.valueOf(1604460327201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("login.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("    ");

    ArrayList<Board> bList=(ArrayList<Board>)request.getAttribute("bList");
    ArrayList<Attachment> tList=(ArrayList<Attachment>)request.getAttribute("tList");
    int bcate= (int)request.getAttribute("bcate");
     
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/34238d14b4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\tfooter,section,.inputtext,nav{display:block;}\t\r\n");
      out.write("\ta{text-decoration:none;\tcolor:black;}\r\n");
      out.write("\tbody{line-height: 1; font-family: 'Open Sans', sans-serif;}\r\n");
      out.write("\t.cardwrap{display:inline-block;margin-left:80px;}\r\n");
      out.write("\tarticle{padding: 100px;\tmargin: 20px;}\r\n");
      out.write("\t#tag_filter{margin-left:220px;border:2px solid lightgray;width:1100px;height:80px;}\r\n");
      out.write("\t.img{display:inline-block;}\r\n");
      out.write("\t#menuname{display:fixed;margin-top:100px; }\r\n");
      out.write("\t.sort{margin-left:1200px;font-size:10px;}\r\n");
      out.write("\t.col{display:inline-block;border: 3px solid black;padding:1px;margin:1px;}\r\n");
      out.write("\t.sortType{cursor:pointer;}\r\n");
      out.write("\t#write{margin-left:1200px;margin-top:100px;padding-top: 1000px;cursor:pointer;\t\t}\r\n");
      out.write("\t.text{margin-top:100px;margin-left:600px;}\r\n");
      out.write("\th2{text-align:center;}\r\n");
      out.write("\t.card h-100:hover{cursor:pointer; }\r\n");
      out.write("\t.col{max-width:\"250px\"; max-height:\"150px\"; min-width:\"250px\"; min-height:\"150px\"; border-radius: 10px;}\r\n");
      out.write("\t#error{margin-left:550px;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- GNB  -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser  = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>GNB</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body, div, span, img, header, nav, ul, li{margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline; text-decoration: none; border-style: none; color: #000000; list-style: none;}\r\n");
      out.write("\tbody{line-height: 1;}\r\n");
      out.write("\t.gnb{width: 100%; height:62px; border-bottom: 1px solid lightgray; min-width: 800px; position: fixed; top: 0; background-color: #fff; text-align: center;}\r\n");
      out.write("\t.gnb-nav ul{width: 80%; max-width: 1000px;  min-width: 800px; margin: auto; display: flex; flex-direction : row; text-align: center;}\r\n");
      out.write("\t#logo {width: 130px;}\r\n");
      out.write("\t.gnb-nav-list{left: 0; width: 90px; cursor: pointer; margin: auto; text-align: center; line-height: 50px;}\r\n");
      out.write("\t.gnb-nav-list:nth-child(1){margin-right: 200px;}\r\n");
      out.write("\t.gnb-nav-list:nth-child(1):hover{border: none; margin-right: 200px;}\r\n");
      out.write("\t.gnb-nav-list:hover {font-weight: bold; border-bottom: 3px solid #41A693;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"gnb\">\r\n");
      out.write("\t\t<nav class=\"gnb-nav\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\"><img id=\"logo\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\" src=\"");
      out.print( request.getContextPath() );
      out.write("/images/common/logo.png\" style=\"cursor: pointer;\"></li>\r\n");
      out.write("\t\t\t\t<li  class=\"gnb-nav-list\" onclick=\"location.href = '");
      out.print( request.getContextPath() );
      out.write("/aboutPage.me'\">About</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\">식당검색</li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/recipe'\">레시피</li>\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/vegiTalk'\">VegiTalk</li>\r\n");
      out.write("\t\t\t\t");
if(loginUser == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/login.me'\">Login</li>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/myPage'\">My Info</li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t <div id=\"menuname\"><h3>&nbsp;&nbsp;RECIPE</h3></div>\r\n");
      out.write("    <br>\r\n");
      out.write("    \t\t");
 if(bList.isEmpty()){ 
      out.write(" \r\n");
      out.write("    \t\t\t\t<article class=\"cardwrap\">\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row row-cols-1 row-cols-sm-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<br><br><br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<h2><font color=\"gray\" id=\"error\">등록된 레시피가 없습니다.</font></h2>\r\n");
      out.write("\t\t\t\t\t\t\t<br><br><br><br><br><br><br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t");
} else{
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \t<div class=\"sort\">\r\n");
      out.write("     \t\t<input type=\"hidden\" name=\"veguntype\" value=\"");
      out.print(bList.get(0).getBoard_cate());
      out.write("\">\r\n");
      out.write("\t\t\t<span class=\"sortType\"><input type=\"hidden\" name=\"cate\" value=\"1\"> 최신순 </span>|\r\n");
      out.write("\t\t\t<span class=\"sortType\"><input type=\"hidden\" name=\"cate\" value=\"2\">좋아요순 </span>|\r\n");
      out.write("\t\t\t<span class=\"sortType\"><input type=\"hidden\" name=\"cate\" value=\"3\">댓글순</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("    \r\n");
      out.write("   \t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('.sortType').click(function(){\r\n");
      out.write("\t\t\t\t\tvar sortType=$(this).children().eq(0).val();\t\t\t//최신순이면 1, 좋아요순이면 2 , 댓글순이면 3\t\r\n");
      out.write(" \t\t\t\t\tvar type=$('.sort').children().eq(0).val();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/recipe.sort?sortType=\" + sortType + \"&type=\" + type + \"&bcate=\" +");
      out.print(bcate);
      out.write(";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t</script>  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t<article class=\"cardwrap\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row row-cols-1 row-cols-sm-5\">\r\n");
      out.write("\t\r\n");
      out.write("  \t");
 if(bList.isEmpty() && tList.isEmpty()){ 
      out.write(" \r\n");
      out.write("\t\t<h2><font color=\"gray\">등록된 레시피가 없습니다.</font></h2>\r\n");
      out.write("\t");
 } else{ 
      out.write("\r\n");
      out.write("\t\t");
 for(int i=0; i < bList.size(); i++){ 
      out.write("\r\n");
      out.write("\t\t\t");
 Board b = bList.get(i); 
      out.write("\r\n");
      out.write("\t\t\t\t");
 
					System.out.println("");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col\">\r\n");
      out.write("    \t\t\t\t<input type=\"hidden\" value=\"");
      out.print(b.getBoard_no() );
      out.write("\">\r\n");
      out.write("    \t\t\t\t\t");
 for(int j=0; j<tList.size(); j++){ 
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t");
 Attachment a = tList.get(j);
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t    \t\t\t");
 if(b.getBoard_no() == a.getBoardNo()){ 
      out.write("\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t\r\n");
      out.write("    \t \t\t\t\t\t\t\t<img src=\"");
      out.print( request.getContextPath());
      out.write("/thumnail_uploadFiles/");
      out.print(a.getAtcName());
      out.write("\" width=\"250px\" height=\"150px\">\r\n");
      out.write("      \t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("      \t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("      \t\t\t\t\t\t");
System.out.println(""); 
      out.write("\r\n");
      out.write("      \t\t\t      <div class=\"card-body\">\r\n");
      out.write("       \t\t\t\t\t <h5>");
      out.print(b.getBoard_title());
      out.write("</h5>\r\n");
      out.write("       \t\t\t\t\t <i class=\"far fa-heart\"></i><b>");
      out.print(b.getBoard_like() );
      out.write("</b>  &nbsp;\r\n");
      out.write("       \t\t \t\t\t\t<i class=\"far fa-comment-dots\"></i><b>");
      out.print(b.getBoard_com() );
      out.write("</b>\r\n");
      out.write("      \t\t\t\t</div>  \t \t   \t \r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("  \t\t");
} 
      out.write(" \r\n");
      out.write("  \t");
} 
      out.write("   \r\n");
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>  \r\n");
      out.write("  \r\n");
      out.write("  \t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('.col').click(function(){\r\n");
      out.write("\t\t\t\tvar bId=$(this).children().eq(0).val();\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/detail.recipe?bId=\" +bId;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write(" \t\t\t\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t");
} 
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 글쓰기 버튼 -->\r\n");
      out.write("  \t ");
if(loginUser == null){ 
      out.write("\r\n");
      out.write("\t\t<span id=\"write\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/recipe/write.png\" height=\"50px\" width=\"50px\" onclick=\"alert('로그인 후 이용가능합니다.')\"></span>\t\r\n");
      out.write("\t");
} else{ 
      out.write("\r\n");
      out.write("\t\t<span id=\"write\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/recipe/write.png\" height=\"50px\" width=\"50px\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/write'\"></span>\t\r\n");
      out.write("\t");
} 
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write(" \t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</article>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"text\">\r\n");
      out.write(" \t\t<form  id=\"select\" action=\"");
      out.print(request.getContextPath() );
      out.write("/search.re\" method=\"post\">\r\n");
      out.write(" \t\t\t");
      out.write("\r\n");
      out.write(" \t\t\t<input type=\"hidden\" value=\"");
      out.print(bcate);
      out.write("\" name=\"type\">\r\n");
      out.write(" \t\t\t<input type=\"text\" class=\"search\" maxlength=\"100\" size=\"50\" name=\"search\"> \r\n");
      out.write(" \t\t\t<input type=\"submit\" value=\"검색\" id=\"search\">\r\n");
      out.write(" \t\t</form>\r\n");
      out.write(" \t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Footer  -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\tfooter{\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\tbottom: 0;\r\n");
      out.write("\t\tpadding-top: 16px;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tbackground: #41A693;\r\n");
      out.write("\t\tmin-width: 500px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 span{\r\n");
      out.write("\t\tfont-size: 16px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tcolor : white;\r\n");
      out.write("\t\tpadding: 2px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.f_div1 p{\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t.f_div1 a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"f_div1\">\r\n");
      out.write("\t\t\t<a href=\"#\"><span>About</span></a>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Privacy</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<span>Feedback</span>\r\n");
      out.write("\t\t\t<span> | </span>\r\n");
      out.write("\t\t\t<a href=\"#\"><span>Top</span></a>\r\n");
      out.write("\t\t\t<p><a href=\"https://github.com/vegiter/vegiter_web\">채채식 팀 GitHub</a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
