/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-02 16:17:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.vegitalk;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import login.model.vo.Member;

public final class writeDiet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/vegitalk/../common/gnb.jsp", Long.valueOf(1604311958000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("login.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>식단 작성</title>\n");
      out.write("<style>\n");
      out.write("\thtml, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video{margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline; text-decoration: none; border-style: none; color: #000000;}\n");
      out.write("\tarticle, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {display: block;}\n");
      out.write("\tbody{line-height: 1;}\n");
      out.write("\tol, ul{list-style: none;}\n");
      out.write("\tblockquote, q {quotes: none;}\n");
      out.write("\tblockquote:before, blockquote:after,\n");
      out.write("\tq:before, q:after {content: ''; content: none;}\n");
      out.write("\ttable{border-collapse: collapse; border-spacing: 0;}\n");
      out.write("\tbutton{outline: none; background-color: white;border-style: none;}\n");
      out.write("\ttextarea{outline: none;padding: 1rem;border-style: none;}\n");
      out.write("\t.wrapper{width: 600px; min-width: 600px; margin: auto; margin-top: 150px; margin-bottom: 100px; overflow: hidden;}\n");
      out.write("\t.write-type {margin: 10px 0; font-size: 14px; color: #ACB5BD;}\n");
      out.write("\t.write-type button{margin-right: 2px; color: #ACB5BD; font-size: 14px;}\n");
      out.write("\t.write-type button:hover{background-color: #F0F3F5; border-radius: 5px;}\n");
      out.write("\t.write-type button:nth-child(1){color: #ACB5BD; font-weight: normal;}\n");
      out.write("\t.write-type button:nth-child(2){color: #41A693;font-weight: bold;}\n");
      out.write("\t.dietList {margin: 20px 0;width: 100%;text-align: center;border-collapse: collapse;}\n");
      out.write("\t.dietList th, td{padding: 15px 5px; border: 4px solid #fff; background-color:  #F0F3F5;;}\n");
      out.write("\t.dietList th{background-color: #41A693;color: #FFF;}\n");
      out.write("\t.dietList .dietList-input{margin: 0; padding: 0;}\n");
      out.write("\tinput{text-align: center; width: 90%;padding: 5px 4px;margin: 5px 0;border-style: none;border-bottom: 1px solid #ACB5BD;outline: none;background-color:  #F0F3F5;}\n");
      out.write("\tinput:nth-child(1){color: #333B3F; font-weight: bold; font-size: 18px;}\n");
      out.write("\tinput:nth-child(2){font-size: 12px;}\n");
      out.write("\t.listBtn{margin: 18px 0;text-align: center;font-size: 24px;color: #ACB5BD;}\n");
      out.write("\t.listBtn>span:hover{color: #41A693;}\n");
      out.write("\t#wirte-area {width: 570px; min-height: 200px; margin: 20px 0; padding: 15px; line-height: 1.5;resize: none;}\n");
      out.write("\t#write-submit-btn{width: 600px;line-height: 3;color: #41A693;background-color: #F2F2F2;}\n");
      out.write("\t#write-submit-btn:hover{color: white;background-color: #41A693;}\n");
      out.write("</style>\n");
      out.write("<script src=\"https://kit.fontawesome.com/34238d14b4.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"");
      out.print( request.getContextPath());
      out.write("/js/jquery-3.5.1.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	Member loginUser  = (Member)session.getAttribute("loginUser");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>GNB</title>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.min.js\"></script>\n");
      out.write("<style>\n");
      out.write("\thtml, body, div, span, img, header, nav, ul, li{margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline; text-decoration: none; border-style: none; color: #000000; list-style: none;}\n");
      out.write("\tbody{line-height: 1; font-family: 'Open Sans', sans-serif;}\n");
      out.write("\t.gnb{width: 100%; height:62px; border-bottom: 1px solid lightgray; min-width: 800px; position: fixed; top: 0; background-color: #fff; text-align: center;}\n");
      out.write("\t.gnb-nav ul{width: 80%; max-width: 1000px;  min-width: 800px; margin: auto; display: flex; flex-direction : row; text-align: center;}\n");
      out.write("\t#logo {width: 130px; right: 0; top: 0; bottom: 0;}\n");
      out.write("\t.gnb-nav-list{left: 0; width: 90px; cursor: pointer; margin: auto; text-align: center; line-height: 51px;}\n");
      out.write("\t.gnb-nav-list:nth-child(1){margin-right: 200px;}\n");
      out.write("\t.gnb-nav-list:nth-child(1):hover{border: none; margin-right: 200px;}\n");
      out.write("\t.gnb-nav-list:hover {font-weight: bold; border-bottom: 3px solid #41A693;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<header class=\"gnb\">\n");
      out.write("\t\t<nav class=\"gnb-nav\">\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\"><img id=\"logo\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\" src=\"");
      out.print( request.getContextPath() );
      out.write("/images/common/logo.png\" style=\"cursor: pointer;\"></li>\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\">About</li>\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\">식당검색</li>\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\">레시피</li>\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/vegiTalk'\">VegiTalk</li>\n");
      out.write("\t\t\t\t");
if(loginUser == null){ 
      out.write("\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/login.me'\">Login</li>\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\n");
      out.write("\t\t\t\t<li class=\"gnb-nav-list\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/myPage'\">My Info</li>\n");
      out.write("\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</nav>\n");
      out.write("\t</header>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("\t\t<div class=\"write-type\">\n");
      out.write("\t\t\t게시글 타입 선택: \n");
      out.write("\t\t\t<button id=\"type-one\" onclick=\"writePost();\">#도란도란</button>\n");
      out.write("\t\t\t<button id=\"type-two\">#식단</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t<form class=\"write\" action=\"");
      out.print( request.getContextPath() );
      out.write("/insertDiet\" method=\"post\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"boardCode\" value=\"2\">\n");
      out.write("\t\t\n");
      out.write("\t\t<table class=\"dietList\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<th>아침</th>\n");
      out.write("\t\t\t\t<th>점심</th>\n");
      out.write("\t\t\t\t<th>저녁</th>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr name=\"diet\">\n");
      out.write("\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"mFood\" placeholder=\"아침 메뉴 입력\">\n");
      out.write("\t\t\t\t\t<input type=\"url\" name=\"mUrl\" placeholder=\"레시피 링크 입력\">\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"lFood\" placeholder=\"점심 메뉴 입력\">\n");
      out.write("\t\t\t\t\t<input type=\"url\" name=\"lUrl\" placeholder=\"레시피 링크 입력\" >\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<input  type=\"text\" name=\"eFood\" placeholder=\"저녁 메뉴 입력\">\n");
      out.write("\t\t\t\t\t<input type=\"url\" name=\"eUrl\"placeholder=\"레시피 링크 입력\">\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\n");
      out.write("\t\t<div class=\"listBtn\">\n");
      out.write("\t\t\t<span id=\"addRow\"><i class=\"far fa-plus-square\"></i></span>&nbsp;\n");
      out.write("\t\t\t<span id=\"removeRow\"><i class=\"far fa-minus-square\"></i></span>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<textarea name=\"boardContent\" id=\"wirte-area\" placeholder=\"게시글을 작성해주세요.\"></textarea>\n");
      out.write("\t\t<button type=\"submit\" name=\"submitBtn\" id=\"write-submit-btn\">등록</button>\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\tfunction writePost(){\n");
      out.write("\t\t$('body').load(\"writePost\");\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$('#addRow').click(function(){\n");
      out.write("\t\t\tvar trCnt = $('.dietList tr[name=\"diet\"]').length;\n");
      out.write("\t\t\tconsole.log(trCnt);\n");
      out.write("\t\t\tif(trCnt > 6) {\n");
      out.write("\t\t\t\talert('최대 7일까지 작성할 수 있어요.')\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\tvar addRow = '<tr name=\"diet\">' +\n");
      out.write("\t\t\t\t\t\t\t '\t<td>' +\n");
      out.write("\t\t\t\t\t\t\t '\t\t<input type=\"text\" name=\"mFood\" placeholder=\"아침 메뉴 입력\">' +\n");
      out.write("\t\t\t\t\t\t\t '\t\t<input type=\"url\" name=\"mUrl\" placeholder=\"레시피 링크 입력\">' +\n");
      out.write("\t\t\t\t\t\t\t '\t</td>' +\n");
      out.write("\t\t\t\t\t\t\t '\t<td>' +\n");
      out.write("\t\t\t\t\t\t\t '\t\t<input type=\"text\" name=\"lFood\" placeholder=\"점심 메뉴 입력\">' +\n");
      out.write("\t\t\t\t\t\t\t '\t\t<input type=\"url\" name=\"lUrl\" placeholder=\"레시피 링크 입력\">' +\n");
      out.write("\t\t\t\t\t\t\t '\t</td>' +\n");
      out.write("\t\t\t\t\t\t\t '\t<td>' +\n");
      out.write("\t\t\t\t\t\t\t '\t\t<input  type=\"text\" name=\"eFood\" placeholder=\"저녁 메뉴 입력\">' +\n");
      out.write("\t\t\t\t\t\t\t '\t\t<input type=\"url\" name=\"eUrl\"placeholder=\"레시피 링크 입력\">' +\n");
      out.write("\t\t\t\t\t\t\t '\t</td>' +\n");
      out.write("\t\t\t\t\t\t\t '</tr>';\n");
      out.write("\t\t\t\t$('tr[name=\"diet\"]:last').after(addRow);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$('#removeRow').click(function(){\n");
      out.write("\t\t\tvar trCnt = $('.dietList tr[name=\"diet\"]').length;\n");
      out.write("\t\t\tif(trCnt > 1) {\n");
      out.write("\t\t\t\t$('tr[name=\"diet\"]:last').remove();\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\talert('하루 이상의 식단을 입력해주세요.');\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$('#write-submit-btn').click(function(){\n");
      out.write("\t\t\tvar content = $('textarea').val();\n");
      out.write("\t\t\tif(content.length == 0) {\n");
      out.write("\t\t\t\talert('게시글 작성해주세요.');\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\treturn true;\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
